"""Traceability completeness checks for generated code.

Verifies provenance banners, @trace tags, version strings, and
content hashes in generated C files.
"""

import re
import logging

from bakec.checks.runner import CheckResult

logger = logging.getLogger("bakec")


def check_provenance_banner(content: str, filename: str) -> list[CheckResult]:
    """TRACE-001: File must have Generated by, Model:, Platform:, and sha256:."""
    required = ["Generated by", "Model:", "Platform:", "sha256:"]
    missing = [r for r in required if r not in content]
    if missing:
        return [CheckResult(
            file=filename,
            line=1,
            severity="error",
            check_id="TRACE-001",
            message=f"Missing provenance fields: {', '.join(missing)}",
            suggestion="Regenerate file with bakeC to include provenance banner",
        )]
    return []


def check_trace_tags(content: str, filename: str) -> list[CheckResult]:
    """TRACE-002: Non-static function definitions must have @trace within 20 lines above."""
    if not filename.endswith('.c'):
        return []

    results = []
    lines = content.split('\n')

    # Find non-static function definitions
    func_pattern = re.compile(r'^(?!static\b)(\w[\w\s\*]*?)\s+(\w+)\s*\([^)]*\)\s*\{', re.MULTILINE)

    for m in func_pattern.finditer(content):
        func_name = m.group(2)
        if func_name in ('if', 'while', 'for', 'switch', 'return'):
            continue
        func_line = content[:m.start()].count('\n')
        # Look for @trace in the 20 lines above
        start_line = max(0, func_line - 20)
        context = '\n'.join(lines[start_line:func_line + 1])
        if '@trace' not in context:
            results.append(CheckResult(
                file=filename,
                line=func_line + 1,
                severity="warning",
                check_id="TRACE-002",
                message=f"Function '{func_name}' has no @trace tag",
                suggestion="Add @trace comment linking to model source",
            ))
    return results


def check_do_not_edit(content: str, filename: str) -> list[CheckResult]:
    """TRACE-003: File must contain DO NOT EDIT warning."""
    if "DO NOT EDIT" not in content:
        return [CheckResult(
            file=filename,
            line=1,
            severity="warning",
            check_id="TRACE-003",
            message="Missing 'DO NOT EDIT' warning",
            suggestion="Add 'DO NOT EDIT' to file banner",
        )]
    return []


def check_version_string(content: str, filename: str) -> list[CheckResult]:
    """TRACE-004: Must contain parseable version like bakeC vX.Y.Z."""
    if not re.search(r'bakeC\s+v\d+', content):
        return [CheckResult(
            file=filename,
            line=1,
            severity="warning",
            check_id="TRACE-004",
            message="No parseable generator version found",
            suggestion="Include 'bakeC vX.Y.Z' in file banner",
        )]
    return []


def check_content_hash(content: str, filename: str) -> list[CheckResult]:
    """TRACE-005: Must contain sha256: followed by at least 8 hex chars."""
    if not re.search(r'sha256:[a-f0-9]{8,}', content):
        return [CheckResult(
            file=filename,
            line=1,
            severity="warning",
            check_id="TRACE-005",
            message="No valid sha256 hash found",
            suggestion="Include sha256 content hash in file banner",
        )]
    return []


def run_traceability_checks(content: str, filename: str) -> list[CheckResult]:
    """Run all traceability checks on a single file.

    Args:
        content: File content string.
        filename: Filename for reporting.

    Returns:
        List of CheckResult findings.
    """
    results: list[CheckResult] = []
    results.extend(check_provenance_banner(content, filename))
    results.extend(check_trace_tags(content, filename))
    results.extend(check_do_not_edit(content, filename))
    results.extend(check_version_string(content, filename))
    results.extend(check_content_hash(content, filename))
    return results
