"""Traceability completeness checks for generated code.

Verifies provenance banners, @trace tags, version strings, and
content hashes in generated C files.
"""

import hashlib
import re
import logging
from pathlib import Path

from bakec.checks.runner import CheckResult

logger = logging.getLogger("bakec")

_MODEL_PATH_RE = re.compile(r'Model:\s+(\S+)\s+\[sha256:([a-f0-9]+)\]')
_PLATFORM_PATH_RE = re.compile(r'Platform:\s+(\S+)\s+\[sha256:([a-f0-9]+)\]')


def check_provenance_banner(content: str, filename: str) -> list[CheckResult]:
    """TRACE-001: File must have Generated by, Model:, Platform:, and sha256:.

    Structural guard — always passes for bakeC-generated output because
    the templates include these fields. Detects hand-created files or
    files from other generators that lack provenance metadata.
    """
    required = ["Generated by", "Model:", "Platform:", "sha256:"]
    missing = [r for r in required if r not in content]
    if missing:
        return [CheckResult(
            file=filename,
            line=1,
            severity="info",
            check_id="TRACE-001",
            message=f"Missing provenance fields: {', '.join(missing)}",
            suggestion="Regenerate file with bakeC to include provenance banner",
        )]
    return []


def check_trace_tags(content: str, filename: str) -> list[CheckResult]:
    """TRACE-002: Non-static function definitions must have @trace within 20 lines above."""
    if not filename.endswith('.c'):
        return []

    results = []
    lines = content.split('\n')

    # Find non-static function definitions
    func_pattern = re.compile(r'^(?!static\b)(\w[\w\s\*]*?)\s+(\w+)\s*\([^)]*\)\s*\{', re.MULTILINE)

    for m in func_pattern.finditer(content):
        func_name = m.group(2)
        if func_name in ('if', 'while', 'for', 'switch', 'return'):
            continue
        func_line = content[:m.start()].count('\n')
        # Look for @trace in the 20 lines above
        start_line = max(0, func_line - 20)
        context = '\n'.join(lines[start_line:func_line + 1])
        if '@trace' not in context:
            results.append(CheckResult(
                file=filename,
                line=func_line + 1,
                severity="warning",
                check_id="TRACE-002",
                message=f"Function '{func_name}' has no @trace tag",
                suggestion="Add @trace comment linking to model source",
            ))
    return results


def check_do_not_edit(content: str, filename: str) -> list[CheckResult]:
    """TRACE-003: File must contain DO NOT EDIT warning.

    Structural guard — always passes for bakeC-generated output because
    the templates include this warning. Detects hand-modified files where
    the warning was removed.
    """
    if "DO NOT EDIT" not in content:
        return [CheckResult(
            file=filename,
            line=1,
            severity="info",
            check_id="TRACE-003",
            message="Missing 'DO NOT EDIT' warning",
            suggestion="Add 'DO NOT EDIT' to file banner",
        )]
    return []


def check_version_string(content: str, filename: str) -> list[CheckResult]:
    """TRACE-004: Must contain parseable version like bakeC vX.Y.Z.

    Structural guard — always passes for bakeC-generated output because
    the templates inject the version string. Detects files from other
    generators or hand-created files.
    """
    if not re.search(r'bakeC\s+v\d+', content):
        return [CheckResult(
            file=filename,
            line=1,
            severity="info",
            check_id="TRACE-004",
            message="No parseable generator version found",
            suggestion="Include 'bakeC vX.Y.Z' in file banner",
        )]
    return []


def check_content_hash(
    content: str,
    filename: str,
    project_root: Path | None = None,
) -> list[CheckResult]:
    """TRACE-005: Verify sha256 hashes in the provenance banner.

    If project_root is provided, extracts Model: and Platform: paths from
    the banner, resolves them relative to project_root, recomputes the
    sha256, and compares against the banner value. Falls back to
    format-only check if source files are inaccessible.
    """
    results: list[CheckResult] = []

    if not re.search(r'sha256:[a-f0-9]{8,}', content):
        results.append(CheckResult(
            file=filename,
            line=1,
            severity="warning",
            check_id="TRACE-005",
            message="No valid sha256 hash found",
            suggestion="Include sha256 content hash in file banner",
        ))
        return results

    if project_root is None:
        return results

    for pattern, label in [
        (_MODEL_PATH_RE, "Model"),
        (_PLATFORM_PATH_RE, "Platform"),
    ]:
        m = pattern.search(content)
        if not m:
            continue
        source_path = project_root / m.group(1)
        banner_hash = m.group(2)
        if not source_path.is_file():
            results.append(CheckResult(
                file=filename,
                line=1,
                severity="info",
                check_id="TRACE-005",
                message=f"{label} source not found at {source_path} — hash not verified",
            ))
            continue
        actual_hash = hashlib.sha256(source_path.read_bytes()).hexdigest()[:len(banner_hash)]
        if actual_hash != banner_hash:
            results.append(CheckResult(
                file=filename,
                line=1,
                severity="error",
                check_id="TRACE-005",
                message=(
                    f"{label} hash mismatch: banner says {banner_hash}, "
                    f"file computes {actual_hash}"
                ),
                suggestion=f"Regenerate file — {label.lower()} source has changed",
            ))

    return results


def run_traceability_checks(
    content: str,
    filename: str,
    project_root: Path | None = None,
) -> list[CheckResult]:
    """Run all traceability checks on a single file.

    Args:
        content: File content string.
        filename: Filename for reporting.
        project_root: Optional project root for resolving source file
            paths and verifying sha256 hashes.

    Returns:
        List of CheckResult findings.
    """
    results: list[CheckResult] = []
    results.extend(check_provenance_banner(content, filename))
    results.extend(check_trace_tags(content, filename))
    results.extend(check_do_not_edit(content, filename))
    results.extend(check_version_string(content, filename))
    results.extend(check_content_hash(content, filename, project_root))
    return results
