"""Tests for platform constraint verification checks."""

from pathlib import Path
from unittest.mock import patch

from bakec.checks.platform_constraints import (
    _extract_platform_path,
    check_real_t_typedef,
    check_literal_suffix,
    check_no_printf,
    check_no_assert,
    check_no_stdlib,
    run_platform_constraint_checks,
)


# --- Helpers ---

CORTEX_M4 = {
    "name": "ARM Cortex-M4",
    "types": {"real_T": "float", "int_T": "int32_t"},
    "constraints": {
        "dynamic_memory": False,
        "printf_allowed": False,
        "assertions": False,
        "floating_point": "single",
    },
    "type_suffix": "f",
}

DESKTOP = {
    "name": "Desktop",
    "types": {"real_T": "double", "int_T": "int32_t"},
    "constraints": {
        "dynamic_memory": False,
        "printf_allowed": True,
        "assertions": True,
        "floating_point": "double",
    },
    "type_suffix": "",
}

BANNER_CORTEX = """\
/**
 * Generated by bakeC v0.1.0
 * Model:    models/lung_mnarx.yaml [sha256:abc123]
 * Platform: platforms/cortex_m4.yaml [sha256:def456]
 */
"""

BANNER_DESKTOP = """\
/**
 * Generated by bakeC v0.1.0
 * Model:    models/lung_mnarx.yaml [sha256:abc123]
 * Platform: platforms/desktop.yaml [sha256:789abc]
 */
"""


# --- Banner extraction ---

def test_extract_platform_path_cortex():
    assert _extract_platform_path(BANNER_CORTEX) == "platforms/cortex_m4.yaml"


def test_extract_platform_path_desktop():
    assert _extract_platform_path(BANNER_DESKTOP) == "platforms/desktop.yaml"


def test_extract_platform_path_missing():
    assert _extract_platform_path("/* no banner */") is None


# --- PLAT-001: real_T typedef ---

def test_real_t_typedef_float_correct():
    code = "typedef float real_T;"
    assert check_real_t_typedef(code, "test_types.h", CORTEX_M4) == []


def test_real_t_typedef_double_correct():
    code = "typedef double real_T;"
    assert check_real_t_typedef(code, "test_types.h", DESKTOP) == []


def test_real_t_typedef_wrong_type():
    code = "typedef double real_T;"
    results = check_real_t_typedef(code, "test_types.h", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-001"
    assert results[0].severity == "error"
    assert "double" in results[0].message
    assert "float" in results[0].message


def test_real_t_typedef_missing():
    code = "typedef int32_t int_T;"
    results = check_real_t_typedef(code, "test_types.h", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-001"


def test_real_t_typedef_skips_non_types_h():
    code = "typedef double real_T;"
    assert check_real_t_typedef(code, "test.c", CORTEX_M4) == []


# --- PLAT-002: Literal suffix ---

def test_literal_suffix_f_correct():
    code = "real_T x = 0.0f;\nreal_T y = 1.5f;"
    assert check_literal_suffix(code, "test.c", CORTEX_M4) == []


def test_literal_suffix_f_missing():
    code = "real_T x = 0.0;\nreal_T y = 1.5;"
    results = check_literal_suffix(code, "test.c", CORTEX_M4)
    assert len(results) == 2
    assert all(r.check_id == "PLAT-002" for r in results)


def test_literal_suffix_unexpected_f():
    code = "real_T x = 0.0f;"
    results = check_literal_suffix(code, "test.c", DESKTOP)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-002"
    assert "unexpected" in results[0].message


def test_literal_suffix_double_correct():
    code = "real_T x = 0.0;\nreal_T y = 1.5;"
    assert check_literal_suffix(code, "test.c", DESKTOP) == []


def test_literal_suffix_skips_non_c():
    code = "real_T x = 0.0;"
    assert check_literal_suffix(code, "test.h", CORTEX_M4) == []


def test_literal_suffix_ignores_comments():
    code = "/* version 0.1 */\nreal_T x = 1.0f;"
    results = check_literal_suffix(code, "test.c", CORTEX_M4)
    assert results == []


# --- PLAT-003: No printf ---

def test_no_printf_clean():
    code = '#include "controller.h"\nvoid step(void) {}'
    assert check_no_printf(code, "test.c", CORTEX_M4) == []


def test_no_printf_stdio_included():
    code = '#include <stdio.h>\nvoid debug(void) {}'
    results = check_no_printf(code, "test.c", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-003"


def test_no_printf_printf_call():
    code = 'void debug(void) { printf("hello"); }'
    results = check_no_printf(code, "test.c", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-003"


def test_no_printf_allowed_on_desktop():
    code = '#include <stdio.h>\nvoid debug(void) { printf("hello"); }'
    assert check_no_printf(code, "test.c", DESKTOP) == []


# --- PLAT-004: No assert ---

def test_no_assert_clean():
    code = 'void step(void) { if (x > 0) {} }'
    assert check_no_assert(code, "test.c", CORTEX_M4) == []


def test_no_assert_header_included():
    code = '#include <assert.h>\nvoid step(void) {}'
    results = check_no_assert(code, "test.c", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-004"


def test_no_assert_call():
    code = 'void step(void) { assert(x > 0); }'
    results = check_no_assert(code, "test.c", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-004"


def test_assert_allowed_on_desktop():
    code = '#include <assert.h>\nvoid step(void) { assert(x > 0); }'
    assert check_no_assert(code, "test.c", DESKTOP) == []


# --- PLAT-005: No stdlib ---

def test_no_stdlib_clean():
    code = '#include <stdint.h>\nvoid step(void) {}'
    assert check_no_stdlib(code, "test.c", CORTEX_M4) == []


def test_no_stdlib_included():
    code = '#include <stdlib.h>\nvoid step(void) {}'
    results = check_no_stdlib(code, "test.c", CORTEX_M4)
    assert len(results) == 1
    assert results[0].check_id == "PLAT-005"


def test_stdlib_with_dynamic_memory_allowed():
    platform = {"constraints": {"dynamic_memory": True}}
    code = '#include <stdlib.h>'
    assert check_no_stdlib(code, "test.c", platform) == []


# --- Orchestrator ---

def test_run_checks_no_banner():
    code = "/* no banner */\ntypedef float real_T;"
    results = run_platform_constraint_checks(code, "test.c", Path("platforms"))
    assert results == []


def test_run_checks_with_real_generated_file(tmp_path):
    """Test against actual generated cortex_m4 files."""
    # Create a mock platform YAML
    platforms_dir = tmp_path / "platforms"
    platforms_dir.mkdir()
    platform_yaml = platforms_dir / "cortex_m4.yaml"
    platform_yaml.write_text(
        "platform:\n"
        "  name: ARM Cortex-M4\n"
        "  types:\n"
        "    real_T: float\n"
        "  constraints:\n"
        "    dynamic_memory: false\n"
        "    printf_allowed: false\n"
        "    assertions: false\n"
        "  type_suffix: 'f'\n"
    )

    # A correct cortex_m4 types header
    types_h = (
        "/**\n"
        " * Platform: platforms/cortex_m4.yaml [sha256:abc123]\n"
        " */\n"
        "typedef float real_T;\n"
    )
    results = run_platform_constraint_checks(types_h, "test_types.h", platforms_dir)
    assert results == []


def test_run_checks_detects_wrong_typedef(tmp_path):
    """Detect wrong real_T on cortex_m4."""
    platforms_dir = tmp_path / "platforms"
    platforms_dir.mkdir()
    platform_yaml = platforms_dir / "cortex_m4.yaml"
    platform_yaml.write_text(
        "platform:\n"
        "  name: ARM Cortex-M4\n"
        "  types:\n"
        "    real_T: float\n"
        "  constraints:\n"
        "    dynamic_memory: false\n"
        "    printf_allowed: false\n"
        "    assertions: false\n"
        "  type_suffix: 'f'\n"
    )

    types_h = (
        "/**\n"
        " * Platform: platforms/cortex_m4.yaml [sha256:abc123]\n"
        " */\n"
        "typedef double real_T;\n"
    )
    results = run_platform_constraint_checks(types_h, "test_types.h", platforms_dir)
    plat001 = [r for r in results if r.check_id == "PLAT-001"]
    assert len(plat001) == 1
    assert plat001[0].severity == "error"


def test_run_checks_platform_not_found():
    code = (
        "/**\n"
        " * Platform: platforms/nonexistent.yaml [sha256:000000]\n"
        " */\n"
    )
    results = run_platform_constraint_checks(code, "test.c", Path("platforms"))
    assert len(results) == 1
    assert results[0].check_id == "PLAT-000"
