"""Tests for traceability completeness checks."""

from bakec.checks.traceability import (
    check_provenance_banner,
    check_trace_tags,
    check_do_not_edit,
    check_version_string,
    check_content_hash,
    run_traceability_checks,
)

VALID_BANNER = """\
/**
 * Generated by bakeC v0.1.0
 * Model:    models/lung_mnarx.yaml [sha256:82625ac76577cf60]
 * Platform: platforms/desktop.yaml [sha256:4355ba8336fc04de]
 * DO NOT EDIT
 */
"""


# --- TRACE-001: Provenance banner ---

def test_provenance_banner_valid():
    assert check_provenance_banner(VALID_BANNER, "test.c") == []


def test_provenance_banner_missing_model():
    content = "Generated by bakeC v0.1.0\nPlatform: x\nsha256:abc\n"
    results = check_provenance_banner(content, "test.c")
    assert len(results) == 1
    assert results[0].check_id == "TRACE-001"
    assert "Model:" in results[0].message


def test_provenance_banner_empty():
    results = check_provenance_banner("int main() { }", "test.c")
    assert len(results) == 1
    assert results[0].severity == "error"


# --- TRACE-002: @trace tags ---

def test_trace_tags_present():
    code = """\
/**
 * @trace models/lung.yaml -> blocks.elastance
 */
void mnarx_lung_step(void)
{
}
"""
    assert check_trace_tags(code, "test.c") == []


def test_trace_tags_missing():
    code = """\
void mnarx_lung_step(void)
{
}
"""
    results = check_trace_tags(code, "test.c")
    assert len(results) == 1
    assert results[0].check_id == "TRACE-002"


def test_trace_tags_skips_headers():
    code = "void mnarx_lung_step(void);"
    assert check_trace_tags(code, "test.h") == []


def test_trace_tags_ignores_static():
    code = """\
static void helper(void)
{
}
"""
    assert check_trace_tags(code, "test.c") == []


# --- TRACE-003: DO NOT EDIT ---

def test_do_not_edit_present():
    assert check_do_not_edit("/* DO NOT EDIT */\nvoid f(void) {}", "test.c") == []


def test_do_not_edit_missing():
    results = check_do_not_edit("void f(void) {}", "test.c")
    assert len(results) == 1
    assert results[0].check_id == "TRACE-003"


# --- TRACE-004: Version string ---

def test_version_string_present():
    assert check_version_string("bakeC v0.1.0\n", "test.c") == []


def test_version_string_missing():
    results = check_version_string("some code\n", "test.c")
    assert len(results) == 1
    assert results[0].check_id == "TRACE-004"


# --- TRACE-005: Content hash ---

def test_content_hash_present():
    assert check_content_hash("sha256:82625ac76577cf60\n", "test.c") == []


def test_content_hash_missing():
    results = check_content_hash("no hash here\n", "test.c")
    assert len(results) == 1
    assert results[0].check_id == "TRACE-005"


def test_content_hash_too_short():
    results = check_content_hash("sha256:abc\n", "test.c")
    assert len(results) == 1


# --- Orchestrator ---

def test_run_traceability_all_pass():
    results = run_traceability_checks(VALID_BANNER, "test.h")
    assert all(r.check_id != "TRACE-001" for r in results)


def test_run_traceability_empty_file():
    results = run_traceability_checks("", "test.c")
    assert len(results) >= 3
